In [1]:
import pandas as pd

In [2]:
file_path = "../data/raw/PLACES__Local_Data_for_Better_Health,_County_Data,_2025_release_20260811.csv"

df = pd.read_csv(file_path)

/var/folders/k5/v8ng94w509nd54z1sbvw8tcr0000gn/T/ipykernel_70427/2561368061.py:3: DtypeWarning: Columns (0: Data_Value_Footnote_Symbol, 1: Data_Value_Footnote) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [3]:
df.head()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,AR,Arkansas,Drew,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,29.9,...,26.6,33.3,"16,945","13,230",5043,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-91.7196579038053 33.5894113647675)
1,2023,AR,Arkansas,Fulton,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.6,...,9.2,11.9,"12,421","9,795",5049,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-91.817888079321 36.3816206347765)
2,2023,AR,Arkansas,Howard,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,31.2,...,27.7,34.8,"12,533","9,311",5061,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-93.9938053308515 34.0889044688856)
3,2023,AR,Arkansas,Miller,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.7,...,4.2,5.3,"42,415","32,396",5091,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.8924281761086 33.3123156126392)
4,2023,AR,Arkansas,Ouachita,BRFSS,Disability,Any disability among adults,%,Crude prevalence,42.8,...,37.9,47.8,"21,793","16,948",5103,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-92.882040791321 33.593253927504)

In [4]:
df.shape

(229298, 22)

In [5]:
df.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'LocationName', 'DataSource',
       'Category', 'Measure', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'TotalPopulation',
       'TotalPop18plus', 'LocationID', 'CategoryID', 'MeasureId',
       'DataValueTypeID', 'Short_Question_Text', 'Geolocation'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 229298 entries, 0 to 229297
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Year                        229298 non-null  int64
 1   StateAbbr                   229298 non-null  str
 2   StateDesc                   229298 non-null  str
 3   LocationName                229218 non-null  str
 4   DataSource                  229298 non-null  str
 5   Category                    229298 non-null  str
 6   Measure                     229298 non-null  str
 7   Data_Value_Unit             229298 non-null  str
 8   Data_Value_Type             229298 non-null  str
 9   Data_Value                  229232 non-null  float64
 10  Data_Value_Footnote_Symbol  80 non-null      str
 11  Data_Value_Footnote         80 non-null      str
 12  Low_Confidence_Limit        229232 non-null  float64
 13  High_Confidence_Limit       229232 non-null  float64
 14  TotalPopulation             229298 non-null  str
 15  TotalPop18plus              229298 non-null  str
 16  LocationID                  229298 non-null  int64
 17  CategoryID                  229298 non-null  str
 18  MeasureId                   229298 non-null  str
 19  DataValueTypeID             229298 non-null  str
 20  Short_Question_Text         229298 non-null  str
 21  Geolocation                 229218 non-null  str
dtypes: float64(3), int64(2), str(17)
memory usage: 38.5 MB

In [7]:
df.isna().sum()

Year                               0
StateAbbr                          0
StateDesc                          0
LocationName                      80
DataSource                         0
Category                           0
Measure                            0
Data_Value_Unit                    0
Data_Value_Type                    0
Data_Value                        66
Data_Value_Footnote_Symbol    229218
Data_Value_Footnote           229218
Low_Confidence_Limit              66
High_Confidence_Limit             66
TotalPopulation                    0
TotalPop18plus                     0
LocationID                         0
CategoryID                         0
MeasureId                          0
DataValueTypeID                    0
Short_Question_Text                0
Geolocation                       80
dtype: int64

In [8]:
df["Category"].value_counts()

Category
Health Outcomes                71366
Prevention                     42534
Disability                     41412
Health-Related Social Needs    32200
Health Risk Behaviors          24038
Health Status                  17748
Name: count, dtype: int64

In [9]:
df["Measure"].nunique()

40

In [10]:
df["Measure"].value_counts()

Measure
Colorectal cancer screening among adults aged 45–75 years                               6290
Mammography use among women aged 50-74 years                                            6290
All teeth lost among adults aged >=65 years                                             6290
Visited dentist or dental clinic in the past year among adults                          6290
Short sleep duration among adults                                                       6290
Arthritis among adults                                                                  5916
Current asthma among adults                                                             5916
Stroke among adults                                                                     5916
Any disability among adults                                                             5916
Obesity among adults                                                                    5916
Diagnosed diabetes among adults                                                         5916
Depression among adults                                                                 5916
Hearing disability among adults                                                         5916
Binge drinking among adults                                                             5916
High blood pressure among adults                                                        5916
Vision disability among adults                                                          5916
Mobility disability among adults                                                        5916
Self-care disability among adults                                                       5916
Frequent mental distress among adults                                                   5916
High cholesterol among adults who have ever been screened                               5916
Frequent physical distress among adults                                                 5916
No leisure-time physical activity among adults                                          5916
Chronic obstructive pulmonary disease among adults                                      5916
Independent living disability among adults                                              5916
Coronary heart disease among adults                                                     5916
Visits to doctor for routine checkup within the past year among adults                  5916
Taking medicine to control high blood pressure among adults with high blood pressure    5916
Current cigarette smoking among adults                                                  5916
Fair or poor self-rated health status among adults                                      5916
Cancer (non-skin) or melanoma among adults                                              5916
Current lack of health insurance among adults aged 18-64 years                          5916
Cognitive disability among adults                                                       5916
Cholesterol screening among adults                                                      5916
Housing insecurity in the past 12 months among adults                                   4600
Utility services shut-off threat in the past 12 months among adults                     4600
Food insecurity in the past 12 months among adults                                      4600
Lack of reliable transportation in the past 12 months among adults                      4600
Lack of social and emotional support among adults                                       4600
Loneliness among adults                                                                 4600
Received food stamps in the past 12 months among adults                                 4600
Name: count, dtype: int64

In [11]:
df["Category"].nunique()

6

In [12]:
df["Category"].unique()

<StringArray>
[            'Health Outcomes',                  'Disability',
       'Health Risk Behaviors',               'Health Status',
                  'Prevention', 'Health-Related Social Needs']
Length: 6, dtype: str

In [13]:
df["StateDesc"].nunique()

52

In [14]:
df["StateDesc"].value_counts()

StateDesc
Texas                   16764
Georgia                 12720
Virginia                10640
Missouri                 9200
Kansas                   8400
Illinois                 8160
North Carolina           8000
Iowa                     7920
Nebraska                 7440
Indiana                  7360
Ohio                     7040
Minnesota                6960
Michigan                 6640
Mississippi              6560
Tennessee                6270
Oklahoma                 6160
Arkansas                 6000
Wisconsin                5760
Alabama                  5360
Louisiana                5120
New York                 4960
California               4640
Montana                  4480
Florida                  4422
West Virginia            4400
South Dakota             4356
North Dakota             4240
Colorado                 4224
South Carolina           3680
Idaho                    3520
New Mexico               2640
Washington               2574
Alaska                   2400
Oregon                   2376
Utah                     2320
Maryland                 1920
New Jersey               1680
Wyoming                  1518
Nevada                   1360
Maine                    1280
Arizona                  1200
Kentucky                 1200
Massachusetts            1120
Vermont                   924
New Hampshire             800
Connecticut               720
Pennsylvania              670
Hawaii                    400
Rhode Island              400
Delaware                  240
United States              80
District of Columbia       80
Name: count, dtype: int64

In [15]:
df["LocationName"].nunique()

1838

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.duplicated(
    subset=["Year", "LocationID", "MeasureId"]
).sum()

np.int64(114649)

In [18]:
duplicates = df[
    df.duplicated(
        subset=["Year", "LocationID", "MeasureId"],
        keep=False
    )
].sort_values(
    ["LocationID", "MeasureId"]
)

duplicates.head(20)

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
640,2023,US,United States,NaN,BRFSS,Prevention,Current lack of health insurance among adults ...,%,Crude prevalence,11.0,...,10.7,11.3,"334,914,895","262,083,034",59,PREVENT,ACCESS2,CrdPrv,Health Insurance,NaN
4485,2023,US,United States,NaN,BRFSS,Prevention,Current lack of health insurance among adults ...,%,Age-adjusted prevalence,11.5,...,11.2,11.9,"334,914,895","262,083,034",59,PREVENT,ACCESS2,AgeAdjPrv,Health Insurance,NaN
8178,2023,US,United States,NaN,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,25.4,...,25.1,25.6,"334,914,895","262,083,034",59,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,NaN
11804,2023,US,United States,NaN,BRFSS,Health Outcomes,Arthritis among adults,%,Age-adjusted prevalence,21.9,...,21.6,22.1,"334,914,895","262,083,034",59,HLTHOUT,ARTHRITIS,AgeAdjPrv,Arthritis,NaN
1151,2023,US,United States,NaN,BRFSS,Health Risk Behaviors,Binge drinking among adults,%,Age-adjusted prevalence,16.6,...,16.3,16.9,"334,914,895","262,083,034",59,RISKBEH,BINGE,AgeAdjPrv,Binge Drinking,NaN
16480,2023,US,United States,NaN,BRFSS,Health Risk Behaviors,Binge drinking among adults,%,Crude prevalence,15.2,...,15.0,15.5,"334,914,895","262,083,034",59,RISKBEH,BINGE,CrdPrv,Binge Drinking,NaN
4734,2023,US,United States,NaN,BRFSS,Health Outcomes,High blood pressure among adults,%,Crude prevalence,34.4,...,34.0,34.7,"334,914,895","262,083,034",59,HLTHOUT,BPHIGH,CrdPrv,High Blood Pressure,NaN
10627,2023,US,United States,NaN,BRFSS,Health Outcomes,High blood pressure among adults,%,Age-adjusted prevalence,30.7,...,30.4,31.0,"334,914,895","262,083,034",59,HLTHOUT,BPHIGH,AgeAdjPrv,High Blood Pressure,NaN
6652,2023,US,United States,NaN,BRFSS,Prevention,Taking medicine to control high blood pressure...,%,Age-adjusted prevalence,57.5,...,56.8,58.2,"334,914,895","262,083,034",59,PREVENT,BPMED,AgeAdjPrv,High Blood Pressure Medication,NaN
15358,2023,US,United States,NaN,BRFSS,Prevention,Taking medicine to control high blood pressure...,%,Crude prevalence,77.0,...,76.5,77.5,"334,914,895","262,083,034",59,PREVENT,BPMED,CrdPrv,High Blood Pressure Medication,NaN
1355,2023,US,United States,NaN,BRFSS,Health Outcomes,Cancer (non-skin) or melanoma among adults,%,Crude prevalence,7.9,...,7.8,8.1,"334,914,895","262,083,034",59,HLTHOUT,CANCER,CrdPrv,Cancer (non-skin) or Melanoma,NaN
13960,2023,US,United States,NaN,BRFSS,Health Outcomes,Cancer (non-skin) or melanoma among adults,%,Age-adjusted prevalence,6.6,...,6.4,6.7,"334,914,895","262,083,034",59,HLTHOUT,CANCER,AgeAdjPrv,Cancer (non-skin) or Melanoma,NaN
7818,2023,US,United States,NaN,BRFSS,Health Outcomes,Current asthma among adults,%,Age-adjusted prevalence,9.8,...,9.6,10.0,"334,914,895","262,083,034",59,HLTHOUT,CASTHMA,AgeAdjPrv,Current Asthma,NaN
9718,2023,US,United States,NaN,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,9.8,...,9.6,10.0,"334,914,895","262,083,034",59,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,NaN
2474,2023,US,United States,NaN,BRFSS,Health Outcomes,Coronary heart disease among adults,%,Crude prevalence,6.4,...,6.2,6.5,"334,914,895","262,083,034",59,HLTHOUT,CHD,CrdPrv,Coronary Heart Disease,NaN
17305,2023,US,United States,NaN,BRFSS,Health Outcomes,Coronary heart disease among adults,%,Age-adjusted prevalence,5.3,...,5.2,5.4,"334,914,895","262,083,034",59,HLTHOUT,CHD,AgeAdjPrv,Coronary Heart Disease,NaN
9063,2023,US,United States,NaN,BRFSS,Prevention,Visits to doctor for routine checkup within th...,%,Age-adjusted prevalence,75.7,...,75.4,76.0,"334,914,895","262,083,034",59,PREVENT,CHECKUP,AgeAdjPrv,Annual Checkup,NaN
13293,2023,US,United States,NaN,BRFSS,Prevention,Visits to doctor for routine checkup within th...,%,Crude prevalence,77.7,...,77.4,78.0,"334,914,895","262,083,034",59,PREVENT,CHECKUP,CrdPrv,Annual Checkup,NaN
12605,2023,US,United States,NaN,BRFSS,Prevention,Cholesterol screening among adults,%,Crude prevalence,87.5,...,87.3,87.8,"334,914,895","262,083,034",59,PREVENT,CHOLSCREEN,CrdPrv,Cholesterol Screening,NaN
16283,2023,US,United States,NaN,BRFSS,Prevention,Cholesterol screening among adults,%,Age-adjusted prevalence,85.6,...,85.3,85.8,"334,914,895","262,083,034",59,PREVENT,CHOLSCREEN,AgeAdjPrv,Cholesterol Screening,NaN

In [19]:
df["Data_Value"].describe()

count    229232.000000
mean         25.988058
std          22.079617
min           1.700000
25%           9.800000
50%          17.600000
75%          34.400000
max          93.300000
Name: Data_Value, dtype: float64

In [20]:
df[
    (df["Data_Value"] < 0) |
    (df["Data_Value"] > 100)
]

Empty DataFrame
Columns: [Year, StateAbbr, StateDesc, LocationName, DataSource, Category, Measure, Data_Value_Unit, Data_Value_Type, Data_Value, Data_Value_Footnote_Symbol, Data_Value_Footnote, Low_Confidence_Limit, High_Confidence_Limit, TotalPopulation, TotalPop18plus, LocationID, CategoryID, MeasureId, DataValueTypeID, Short_Question_Text, Geolocation]
Index: []

[0 rows x 22 columns]

In [21]:
pd.crosstab(
    df["Category"],
    df["Data_Value_Type"]
)

Data_Value_Type              Age-adjusted prevalence  Crude prevalence
Category
Disability                                     20706             20706
Health Outcomes                                35683             35683
Health Risk Behaviors                          12019             12019
Health Status                                   8874              8874
Health-Related Social Needs                    16100             16100
Prevention                                     21267             21267

In [22]:
pd.crosstab(
    df["Category"],
    df["Data_Value_Unit"]
)

Data_Value_Unit                  %
Category
Disability                   41412
Health Outcomes              71366
Health Risk Behaviors        24038
Health Status                17748
Health-Related Social Needs  32200
Prevention                   42534

In [24]:
df.duplicated(
    subset=[
        "Year",
        "LocationID",
        "MeasureId",
        "DataValueTypeID"
    ]
).sum()

np.int64(0)

In [25]:
missing_values = df[df["Data_Value"].isna()]

missing_values[
    [
        "Year",
        "StateAbbr",
        "StateDesc",
        "LocationName",
        "Category",
        "Measure",
        "MeasureId",
        "DataValueTypeID",
        "Data_Value",
        "Data_Value_Footnote_Symbol",
        "Data_Value_Footnote"
    ]
]

,Year,StateAbbr,StateDesc,LocationName,Category,Measure,MeasureId,DataValueTypeID,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote
179442,2023,TX,Texas,Loving,Health Risk Behaviors,No leisure-time physical activity among adults,LPA,AgeAdjPrv,NaN,*,Estimates suppressed for population less than 50
179924,2023,TX,Texas,Loving,Prevention,Current lack of health insurance among adults ...,ACCESS2,CrdPrv,NaN,*,Estimates suppressed for population less than 50
179946,2023,TX,Texas,Loving,Health Outcomes,Current asthma among adults,CASTHMA,CrdPrv,NaN,*,Estimates suppressed for population less than 50
180119,2023,TX,Texas,Loving,Health Risk Behaviors,No leisure-time physical activity among adults,LPA,CrdPrv,NaN,*,Estimates suppressed for population less than 50
180150,2022,TX,Texas,Loving,Health Risk Behaviors,Short sleep duration among adults,SLEEP,AgeAdjPrv,NaN,*,Estimates suppressed for population less than 50
...,...,...,...,...,...,...,...,...,...,...,...
195815,2023,TX,Texas,Loving,Health Outcomes,Obesity among adults,OBESITY,CrdPrv,NaN,*,Estimates suppressed for population less than 50
196112,2023,TX,Texas,Loving,Disability,Any disability among adults,DISABILITY,AgeAdjPrv,NaN,*,Estimates suppressed for population less than 50
196572,2023,TX,Texas,Loving,Health Outcomes,Chronic obstructive pulmonary disease among ad...,COPD,CrdPrv,NaN,*,Estimates suppressed for population less than 50
196846,2023,TX,Texas,Loving,Health Outcomes,Arthritis among adults,ARTHRITIS,AgeAdjPrv,NaN,*,Estimates suppressed for population less than 50
196939,2023,TX,Texas,Loving,Disability,Self-care disability among adults,SELFCARE,CrdPrv,NaN,*,Estimates suppressed for population less than 50

In [26]:
missing_values["Data_Value_Footnote"].value_counts(dropna=False)

Data_Value_Footnote
Estimates suppressed for population less than 50    66
Name: count, dtype: int64

In [27]:
missing_values["Data_Value_Footnote_Symbol"].value_counts(dropna=False)

Data_Value_Footnote_Symbol
*    66
Name: count, dtype: int64

In [28]:
df.groupby("StateAbbr")["LocationID"].nunique().sort_values()

StateAbbr
DC      1
US      1
DE      3
HI      5
RI      5
CT      9
NH     10
MA     14
VT     14
AZ     15
ME     16
NV     17
NJ     21
WY     23
MD     24
UT     29
AK     30
NM     33
OR     36
WA     39
ID     44
SC     46
ND     53
WV     55
MT     56
CA     58
NY     62
CO     64
LA     64
SD     66
FL     67
AL     67
PA     67
WI     72
AR     75
OK     77
MS     82
MI     83
MN     87
OH     88
IN     92
NE     93
TN     95
IA     99
NC    100
IL    102
KS    105
MO    115
KY    120
VA    133
GA    159
TX    254
Name: LocationID, dtype: int64

In [29]:
df[df["StateAbbr"] == "US"]["MeasureId"].nunique()

40

In [30]:
df[df["StateAbbr"] != "US"]["LocationID"].nunique()

3144

In [31]:
missing_values["Data_Value_Footnote"].value_counts(dropna=False)

Data_Value_Footnote
Estimates suppressed for population less than 50    66
Name: count, dtype: int64

In [32]:
processed_df = pd.read_csv(
    "../data/processed/places_county_clean.csv"
)

processed_df.head()

/var/folders/k5/v8ng94w509nd54z1sbvw8tcr0000gn/T/ipykernel_70427/4074205326.py:1: DtypeWarning: Columns (0: data_value_footnote_symbol, 1: data_value_footnote) have mixed types. Specify dtype option on import or set low_memory=False.
  processed_df = pd.read_csv(

,year,stateabbr,statedesc,locationname,datasource,category,measure,data_value_unit,data_value_type,data_value,...,low_confidence_limit,high_confidence_limit,totalpopulation,totalpop18plus,locationid,categoryid,measureid,datavaluetypeid,short_question_text,geolocation
0,2023,AR,Arkansas,Drew,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,29.9,...,26.6,33.3,16945,13230,5043,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-91.7196579038053 33.5894113647675)
1,2023,AR,Arkansas,Fulton,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.6,...,9.2,11.9,12421,9795,5049,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-91.817888079321 36.3816206347765)
2,2023,AR,Arkansas,Howard,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,31.2,...,27.7,34.8,12533,9311,5061,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-93.9938053308515 34.0889044688856)
3,2023,AR,Arkansas,Miller,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.7,...,4.2,5.3,42415,32396,5091,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.8924281761086 33.3123156126392)
4,2023,AR,Arkansas,Ouachita,BRFSS,Disability,Any disability among adults,%,Crude prevalence,42.8,...,37.9,47.8,21793,16948,5103,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-92.882040791321 33.593253927504)

In [33]:
processed_df.shape

(229218, 22)

In [34]:
processed_df["stateabbr"].unique()

<StringArray>
['AR', 'CA', 'CO', 'FL', 'GA', 'ID', 'IL', 'IN', 'IA', 'KS', 'LA', 'ME', 'MD',
 'MI', 'MN', 'NE', 'NV', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'SC',
 'SD', 'TN', 'TX', 'UT', 'VA', 'WA', 'WV', 'WI', 'AL', 'AZ', 'AK', 'CT', 'DE',
 'DC', 'HI', 'MA', 'KY', 'MS', 'MT', 'MO', 'NH', 'RI', 'PA', 'VT', 'WY']
Length: 51, dtype: str

In [35]:
processed_df["totalpopulation"].dtype

dtype('int64')

In [36]:
processed_df["category"].value_counts()

category
Health Outcomes                71342
Prevention                     42520
Disability                     41398
Health-Related Social Needs    32186
Health Risk Behaviors          24030
Health Status                  17742
Name: count, dtype: int64

In [37]:
processed_df["measure"].nunique()

40

In [38]:
processed_df["measure"].value_counts()

measure
Colorectal cancer screening among adults aged 45–75 years                               6288
Mammography use among women aged 50-74 years                                            6288
All teeth lost among adults aged >=65 years                                             6288
Visited dentist or dental clinic in the past year among adults                          6288
Short sleep duration among adults                                                       6288
Arthritis among adults                                                                  5914
Current asthma among adults                                                             5914
Stroke among adults                                                                     5914
Any disability among adults                                                             5914
Obesity among adults                                                                    5914
Diagnosed diabetes among adults                                                         5914
Depression among adults                                                                 5914
Hearing disability among adults                                                         5914
Binge drinking among adults                                                             5914
High blood pressure among adults                                                        5914
Vision disability among adults                                                          5914
Mobility disability among adults                                                        5914
Self-care disability among adults                                                       5914
Frequent mental distress among adults                                                   5914
High cholesterol among adults who have ever been screened                               5914
Frequent physical distress among adults                                                 5914
No leisure-time physical activity among adults                                          5914
Chronic obstructive pulmonary disease among adults                                      5914
Independent living disability among adults                                              5914
Coronary heart disease among adults                                                     5914
Visits to doctor for routine checkup within the past year among adults                  5914
Taking medicine to control high blood pressure among adults with high blood pressure    5914
Current cigarette smoking among adults                                                  5914
Fair or poor self-rated health status among adults                                      5914
Cancer (non-skin) or melanoma among adults                                              5914
Current lack of health insurance among adults aged 18-64 years                          5914
Cognitive disability among adults                                                       5914
Cholesterol screening among adults                                                      5914
Housing insecurity in the past 12 months among adults                                   4598
Utility services shut-off threat in the past 12 months among adults                     4598
Food insecurity in the past 12 months among adults                                      4598
Lack of reliable transportation in the past 12 months among adults                      4598
Lack of social and emotional support among adults                                       4598
Loneliness among adults                                                                 4598
Received food stamps in the past 12 months among adults                                 4598
Name: count, dtype: int64

In [39]:
measure_summary = (
    processed_df
    .groupby(["category", "measure"])
    .agg(
        observations=("data_value", "count"),
        mean_prevalence=("data_value", "mean"),
        median_prevalence=("data_value", "median"),
        min_prevalence=("data_value", "min"),
        max_prevalence=("data_value", "max")
    )
    .reset_index()
)

measure_summary

,category,measure,observations,mean_prevalence,median_prevalence,min_prevalence,max_prevalence
0,Disability,Any disability among adults,5912,33.486282,33.10,18.9,52.3
1,Disability,Cognitive disability among adults,5912,16.148647,15.90,9.1,28.2
2,Disability,Hearing disability among adults,5912,7.804347,7.50,3.9,16.1
3,Disability,Independent living disability among adults,5912,9.167371,8.90,4.4,20.8
4,Disability,Mobility disability among adults,5912,15.105734,14.70,7.0,31.4
5,Disability,Self-care disability among adults,5912,4.193995,4.00,1.7,10.8
6,Disability,Vision disability among adults,5912,5.641576,5.30,2.5,17.5
7,Health Outcomes,All teeth lost among adults aged >=65 years,6286,15.989898,15.20,3.8,44.6
8,Health Outcomes,Arthritis among adults,5912,27.178062,26.70,12.7,45.8
9,Health Outcomes,Cancer (non-skin) or melanoma among adults,5912,8.008457,7.50,3.2,17.8
10,Health Outcomes,Chronic obstructive pulmonary disease among ad...,5912,7.729212,7.50,3.2,17.6
11,Health Outcomes,Coronary heart disease among adults,5912,6.884151,6.60,3.0,13.3
12,Health Outcomes,Current asthma among adults,5912,10.661164,10.60,7.8,15.3
13,Health Outcomes,Depression among adults,5912,23.482882,23.30,12.3,36.2
14,Health Outcomes,Diagnosed diabetes among adults,5912,12.403281,12.10,4.9,27.1
15,Health Outcomes,High blood pressure among adults,5912,36.128671,35.70,17.3,59.8
16,Health Outcomes,High cholesterol among adults who have ever be...,5912,35.071752,34.50,21.2,51.4
17,Health Outcomes,Obesity among adults,5912,37.525507,38.10,16.7,54.0
18,Health Outcomes,Stroke among adults,5912,3.684912,3.50,1.7,8.4
19,Health Risk Behaviors,Binge drinking among adults,5912,16.706072,16.50,8.2,26.3
20,Health Risk Behaviors,Current cigarette smoking among adults,5912,16.080700,15.80,6.4,40.3
21,Health Risk Behaviors,No leisure-time physical activity among adults,5912,27.734743,27.30,12.1,49.5
22,Health Risk Behaviors,Short sleep duration among adults,6286,36.663713,36.90,24.1,51.0
23,Health Status,Fair or poor self-rated health status among ad...,5912,21.349154,20.60,10.4,42.7
24,Health Status,Frequent mental distress among adults,5912,17.866001,17.90,11.5,26.6
25,Health Status,Frequent physical distress among adults,5912,14.391103,14.30,8.7,23.6
26,Health-Related Social Needs,Food insecurity in the past 12 months among ad...,4598,16.782971,15.30,5.7,46.8
27,Health-Related Social Needs,Housing insecurity in the past 12 months among...,4598,13.216464,12.20,5.6,33.6
28,Health-Related Social Needs,Lack of reliable transportation in the past 12...,4598,9.098565,8.40,3.9,27.6
29,Health-Related Social Needs,Lack of social and emotional support among adults,4598,23.850348,23.40,16.3,37.9
30,Health-Related Social Needs,Loneliness among adults,4598,33.510309,33.30,25.7,43.8
31,Health-Related Social Needs,Received food stamps in the past 12 months amo...,4598,13.614615,12.40,3.5,46.6
32,Health-Related Social Needs,Utility services shut-off threat in the past 1...,4598,9.157286,8.40,3.5,27.8
33,Prevention,Cholesterol screening among adults,5912,84.177267,84.30,63.7,93.3
34,Prevention,Colorectal cancer screening among adults aged ...,6286,60.664349,60.70,39.4,79.1
35,Prevention,Current lack of health insurance among adults ...,5912,11.407544,10.20,3.6,43.7
36,Prevention,Mammography use among women aged 50-74 years,6286,73.676599,74.00,48.5,87.1
37,Prevention,Taking medicine to control high blood pressure...,5912,68.042591,67.05,48.0,87.2
38,Prevention,Visited dentist or dental clinic in the past y...,6286,57.787130,59.50,4.9,78.3
39,Prevention,Visits to doctor for routine checkup within th...,5912,76.276184,76.80,60.2,87.0

In [40]:
measure_summary.sort_values(
    "mean_prevalence",
    ascending=False
).head(20)

,category,measure,observations,mean_prevalence,median_prevalence,min_prevalence,max_prevalence
33,Prevention,Cholesterol screening among adults,5912,84.177267,84.30,63.7,93.3
39,Prevention,Visits to doctor for routine checkup within th...,5912,76.276184,76.80,60.2,87.0
36,Prevention,Mammography use among women aged 50-74 years,6286,73.676599,74.00,48.5,87.1
37,Prevention,Taking medicine to control high blood pressure...,5912,68.042591,67.05,48.0,87.2
34,Prevention,Colorectal cancer screening among adults aged ...,6286,60.664349,60.70,39.4,79.1
38,Prevention,Visited dentist or dental clinic in the past y...,6286,57.787130,59.50,4.9,78.3
17,Health Outcomes,Obesity among adults,5912,37.525507,38.10,16.7,54.0
22,Health Risk Behaviors,Short sleep duration among adults,6286,36.663713,36.90,24.1,51.0
15,Health Outcomes,High blood pressure among adults,5912,36.128671,35.70,17.3,59.8
16,Health Outcomes,High cholesterol among adults who have ever be...,5912,35.071752,34.50,21.2,51.4
30,Health-Related Social Needs,Loneliness among adults,4598,33.510309,33.30,25.7,43.8
0,Disability,Any disability among adults,5912,33.486282,33.10,18.9,52.3
21,Health Risk Behaviors,No leisure-time physical activity among adults,5912,27.734743,27.30,12.1,49.5
8,Health Outcomes,Arthritis among adults,5912,27.178062,26.70,12.7,45.8
29,Health-Related Social Needs,Lack of social and emotional support among adults,4598,23.850348,23.40,16.3,37.9
13,Health Outcomes,Depression among adults,5912,23.482882,23.30,12.3,36.2
23,Health Status,Fair or poor self-rated health status among ad...,5912,21.349154,20.60,10.4,42.7
24,Health Status,Frequent mental distress among adults,5912,17.866001,17.90,11.5,26.6
26,Health-Related Social Needs,Food insecurity in the past 12 months among ad...,4598,16.782971,15.30,5.7,46.8
19,Health Risk Behaviors,Binge drinking among adults,5912,16.706072,16.50,8.2,26.3

In [41]:
processed_df["datavaluetypeid"].value_counts()

datavaluetypeid
CrdPrv       114609
AgeAdjPrv    114609
Name: count, dtype: int64

In [42]:
prevalence_comparison = (
    processed_df
    .groupby(
        ["measure", "datavaluetypeid"]
    )["data_value"]
    .mean()
    .reset_index()
)

prevalence_comparison

,measure,datavaluetypeid,data_value
0,All teeth lost among adults aged >=65 years,AgeAdjPrv,16.145434
1,All teeth lost among adults aged >=65 years,CrdPrv,15.834362
2,Any disability among adults,AgeAdjPrv,32.362077
3,Any disability among adults,CrdPrv,34.610487
4,Arthritis among adults,AgeAdjPrv,24.598613
...,...,...,...
75,Vision disability among adults,CrdPrv,5.877774
76,Visited dentist or dental clinic in the past y...,AgeAdjPrv,57.321699
77,Visited dentist or dental clinic in the past y...,CrdPrv,58.252561
78,Visits to doctor for routine checkup within th...,AgeAdjPrv,74.851894
79,Visits to doctor for routine checkup within th...,CrdPrv,77.700474

In [43]:
prevalence_comparison.sort_values(
    "measure"
)

,measure,datavaluetypeid,data_value
0,All teeth lost among adults aged >=65 years,AgeAdjPrv,16.145434
1,All teeth lost among adults aged >=65 years,CrdPrv,15.834362
2,Any disability among adults,AgeAdjPrv,32.362077
3,Any disability among adults,CrdPrv,34.610487
4,Arthritis among adults,AgeAdjPrv,24.598613
...,...,...,...
75,Vision disability among adults,CrdPrv,5.877774
76,Visited dentist or dental clinic in the past y...,AgeAdjPrv,57.321699
77,Visited dentist or dental clinic in the past y...,CrdPrv,58.252561
78,Visits to doctor for routine checkup within th...,AgeAdjPrv,74.851894
79,Visits to doctor for routine checkup within th...,CrdPrv,77.700474

In [44]:
state_summary = (
    processed_df
    .groupby(["stateabbr", "statedesc"])
    .agg(
        mean_prevalence=("data_value", "mean"),
        median_prevalence=("data_value", "median"),
        measures=("measureid", "nunique"),
        counties=("locationid", "nunique")
    )
    .reset_index()
)

state_summary.sort_values(
    "mean_prevalence",
    ascending=False
).head(10)

,stateabbr,statedesc,mean_prevalence,median_prevalence,measures,counties
38,PA,Pennsylvania,51.387463,60.45,5,67
17,KY,Kentucky,50.181583,53.75,5,120
42,TN,Tennessee,28.801308,20.80,33,95
18,LA,Louisiana,28.589336,21.50,40,64
49,WV,West Virginia,28.100477,20.70,40,55
1,AL,Alabama,27.680690,19.50,40,67
2,AR,Arkansas,27.385867,20.00,40,75
43,TX,Texas,27.205995,18.80,33,254
9,FL,Florida,27.148711,17.90,33,67
25,MS,Mississippi,27.057165,19.40,40,82

In [45]:
age_adjustment = (
    processed_df
    .pivot_table(
        index="measure",
        columns="datavaluetypeid",
        values="data_value",
        aggfunc="mean"
    )
    .reset_index()
)

age_adjustment["difference"] = (
    age_adjustment["CrdPrv"]
    - age_adjustment["AgeAdjPrv"]
)

age_adjustment.sort_values(
    "difference",
    ascending=False
)

datavaluetypeid,measure,AgeAdjPrv,CrdPrv,difference
35,Taking medicine to control high blood pressure...,58.126793,77.958390,19.831597
8,Colorectal cancer screening among adults aged ...,57.498218,63.830480,6.332262
21,High cholesterol among adults who have ever be...,31.997801,38.145704,6.147903
20,High blood pressure among adults,33.537483,38.719858,5.182375
2,Arthritis among adults,24.598613,29.757510,5.158897
39,Visits to doctor for routine checkup within th...,74.851894,77.700474,2.848579
28,Mobility disability among adults,13.697530,16.513938,2.816407
5,Cholesterol screening among adults,82.918403,85.436130,2.517727
14,Diagnosed diabetes among adults,11.168200,13.638363,2.470162
1,Any disability among adults,32.362077,34.610487,2.248410
4,Cancer (non-skin) or melanoma among adults,6.969452,9.047463,2.078011
9,Coronary heart disease among adults,5.974831,7.793471,1.818640
19,Hearing disability among adults,6.983627,8.625068,1.641441
6,Chronic obstructive pulmonary disease among ad...,6.986942,8.471482,1.484540
29,No leisure-time physical activity among adults,27.018843,28.450643,1.431800
15,Fair or poor self-rated health status among ad...,20.685622,22.012686,1.327064
18,Frequent physical distress among adults,13.833119,14.949087,1.115968
38,Visited dentist or dental clinic in the past y...,57.321699,58.252561,0.930862
34,Stroke among adults,3.270670,4.099154,0.828484
27,Mammography use among women aged 50-74 years,73.335571,74.017626,0.682055
32,Self-care disability among adults,3.945129,4.442862,0.497733
37,Vision disability among adults,5.405379,5.877774,0.472395
23,Independent living disability among adults,9.041610,9.293133,0.251522
10,Current asthma among adults,10.716678,10.605650,-0.111028
30,Obesity among adults,37.627267,37.423748,-0.203518
0,All teeth lost among adults aged >=65 years,16.145434,15.834362,-0.311072
11,Current cigarette smoking among adults,16.342693,15.818708,-0.523985
12,Current lack of health insurance among adults ...,11.673579,11.141509,-0.532070
24,Lack of reliable transportation in the past 12...,9.448630,8.748499,-0.700130
31,Received food stamps in the past 12 months amo...,14.048673,13.180557,-0.868117
25,Lack of social and emotional support among adults,24.288995,23.411701,-0.877294
7,Cognitive disability among adults,16.593031,15.704263,-0.888769
36,Utility services shut-off threat in the past 1...,9.670900,8.643671,-1.027229
16,Food insecurity in the past 12 months among ad...,17.298391,16.267551,-1.030839
13,Depression among adults,24.062449,22.903315,-1.159134
33,Short sleep duration among adults,37.308018,36.019408,-1.288610
26,Loneliness among adults,34.192997,32.827621,-1.365376
17,Frequent mental distress among adults,18.607070,17.124932,-1.482138
22,Housing insecurity in the past 12 months among...,13.968943,12.463984,-1.504959
3,Binge drinking among adults,17.781326,15.630819,-2.150507

In [46]:
age_adjustment.sort_values(
    "difference",
    ascending=False
).head(10)

datavaluetypeid,measure,AgeAdjPrv,CrdPrv,difference
35,Taking medicine to control high blood pressure...,58.126793,77.958390,19.831597
8,Colorectal cancer screening among adults aged ...,57.498218,63.830480,6.332262
21,High cholesterol among adults who have ever be...,31.997801,38.145704,6.147903
20,High blood pressure among adults,33.537483,38.719858,5.182375
2,Arthritis among adults,24.598613,29.757510,5.158897
39,Visits to doctor for routine checkup within th...,74.851894,77.700474,2.848579
28,Mobility disability among adults,13.697530,16.513938,2.816407
5,Cholesterol screening among adults,82.918403,85.436130,2.517727
14,Diagnosed diabetes among adults,11.168200,13.638363,2.470162
1,Any disability among adults,32.362077,34.610487,2.248410

In [47]:
age_adjustment.sort_values(
    "difference",
    ascending=True
).head(10)

datavaluetypeid,measure,AgeAdjPrv,CrdPrv,difference
3,Binge drinking among adults,17.781326,15.630819,-2.150507
22,Housing insecurity in the past 12 months among...,13.968943,12.463984,-1.504959
17,Frequent mental distress among adults,18.607070,17.124932,-1.482138
26,Loneliness among adults,34.192997,32.827621,-1.365376
33,Short sleep duration among adults,37.308018,36.019408,-1.288610
13,Depression among adults,24.062449,22.903315,-1.159134
16,Food insecurity in the past 12 months among ad...,17.298391,16.267551,-1.030839
36,Utility services shut-off threat in the past 1...,9.670900,8.643671,-1.027229
7,Cognitive disability among adults,16.593031,15.704263,-0.888769
25,Lack of social and emotional support among adults,24.288995,23.411701,-0.877294

In [48]:
county_counts = (
    processed_df
    .groupby(["stateabbr", "statedesc"])["locationid"]
    .nunique()
    .reset_index(name="county_count")
)

county_counts.sort_values(
    "county_count",
    ascending=False
).head(15)

   stateabbr       statedesc  county_count
43        TX           Texas           254
10        GA         Georgia           159
45        VA        Virginia           133
17        KY        Kentucky           120
24        MO        Missouri           115
16        KS          Kansas           105
14        IL        Illinois           102
27        NC  North Carolina           100
12        IA            Iowa            99
42        TN       Tennessee            95
29        NE        Nebraska            93
15        IN         Indiana            92
35        OH            Ohio            88
23        MN       Minnesota            87
22        MI        Michigan            83

In [49]:
indicator_metadata = (
    processed_df[
        [
            "measureid",
            "measure",
            "category",
            "datavaluetypeid"
        ]
    ]
    .drop_duplicates()
    .sort_values(["category", "measureid"])
)

indicator_metadata

,measureid,measure,category,datavaluetypeid
269,COGNITION,Cognitive disability among adults,Disability,AgeAdjPrv
270,COGNITION,Cognitive disability among adults,Disability,CrdPrv
4,DISABILITY,Any disability among adults,Disability,CrdPrv
306,DISABILITY,Any disability among adults,Disability,AgeAdjPrv
19,HEARING,Hearing disability among adults,Disability,CrdPrv
...,...,...,...,...
320,COLON_SCREEN,Colorectal cancer screening among adults aged ...,Prevention,AgeAdjPrv
256,DENTAL,Visited dentist or dental clinic in the past y...,Prevention,CrdPrv
294,DENTAL,Visited dentist or dental clinic in the past y...,Prevention,AgeAdjPrv
224,MAMMOUSE,Mammography use among women aged 50-74 years,Prevention,AgeAdjPrv
259,MAMMOUSE,Mammography use among women aged 50-74 years,Prevention,CrdPrv

In [50]:
indicator_metadata[
    indicator_metadata["datavaluetypeid"] == "AgeAdjPrv"
]

,measureid,measure,category,datavaluetypeid
269,COGNITION,Cognitive disability among adults,Disability,AgeAdjPrv
306,DISABILITY,Any disability among adults,Disability,AgeAdjPrv
266,HEARING,Hearing disability among adults,Disability,AgeAdjPrv
298,INDEPLIVE,Independent living disability among adults,Disability,AgeAdjPrv
216,MOBILITY,Mobility disability among adults,Disability,AgeAdjPrv
239,SELFCARE,Self-care disability among adults,Disability,AgeAdjPrv
276,VISION,Vision disability among adults,Disability,AgeAdjPrv
16,ARTHRITIS,Arthritis among adults,Health Outcomes,AgeAdjPrv
238,BPHIGH,High blood pressure among adults,Health Outcomes,AgeAdjPrv
248,CANCER,Cancer (non-skin) or melanoma among adults,Health Outcomes,AgeAdjPrv
268,CASTHMA,Current asthma among adults,Health Outcomes,AgeAdjPrv
223,CHD,Coronary heart disease among adults,Health Outcomes,AgeAdjPrv
221,COPD,Chronic obstructive pulmonary disease among ad...,Health Outcomes,AgeAdjPrv
127,DEPRESSION,Depression among adults,Health Outcomes,AgeAdjPrv
254,DIABETES,Diagnosed diabetes among adults,Health Outcomes,AgeAdjPrv
212,HIGHCHOL,High cholesterol among adults who have ever be...,Health Outcomes,AgeAdjPrv
20,OBESITY,Obesity among adults,Health Outcomes,AgeAdjPrv
17,STROKE,Stroke among adults,Health Outcomes,AgeAdjPrv
235,TEETHLOST,All teeth lost among adults aged >=65 years,Health Outcomes,AgeAdjPrv
213,BINGE,Binge drinking among adults,Health Risk Behaviors,AgeAdjPrv
271,CSMOKING,Current cigarette smoking among adults,Health Risk Behaviors,AgeAdjPrv
284,LPA,No leisure-time physical activity among adults,Health Risk Behaviors,AgeAdjPrv
336,SLEEP,Short sleep duration among adults,Health Risk Behaviors,AgeAdjPrv
257,GHLTH,Fair or poor self-rated health status among ad...,Health Status,AgeAdjPrv
210,MHLTH,Frequent mental distress among adults,Health Status,AgeAdjPrv
274,PHLTH,Frequent physical distress among adults,Health Status,AgeAdjPrv
255,EMOTIONSPT,Lack of social and emotional support among adults,Health-Related Social Needs,AgeAdjPrv
230,FOODINSECU,Food insecurity in the past 12 months among ad...,Health-Related Social Needs,AgeAdjPrv
262,FOODSTAMP,Received food stamps in the past 12 months amo...,Health-Related Social Needs,AgeAdjPrv
286,HOUSINSECU,Housing insecurity in the past 12 months among...,Health-Related Social Needs,AgeAdjPrv
355,LACKTRPT,Lack of reliable transportation in the past 12...,Health-Related Social Needs,AgeAdjPrv
333,LONELINESS,Loneliness among adults,Health-Related Social Needs,AgeAdjPrv
229,SHUTUTILITY,Utility services shut-off threat in the past 1...,Health-Related Social Needs,AgeAdjPrv
401,ACCESS2,Current lack of health insurance among adults ...,Prevention,AgeAdjPrv
226,BPMED,Taking medicine to control high blood pressure...,Prevention,AgeAdjPrv
225,CHECKUP,Visits to doctor for routine checkup within th...,Prevention,AgeAdjPrv
317,CHOLSCREEN,Cholesterol screening among adults,Prevention,AgeAdjPrv
320,COLON_SCREEN,Colorectal cancer screening among adults aged ...,Prevention,AgeAdjPrv
294,DENTAL,Visited dentist or dental clinic in the past y...,Prevention,AgeAdjPrv
224,MAMMOUSE,Mammography use among women aged 50-74 years,Prevention,AgeAdjPrv

In [51]:
measure_variability = (
    processed_df[
        processed_df["datavaluetypeid"] == "AgeAdjPrv"
    ]
    .groupby(
        ["measureid", "measure", "category"]
    )
    .agg(
        mean=("data_value", "mean"),
        median=("data_value", "median"),
        std=("data_value", "std"),
        minimum=("data_value", "min"),
        maximum=("data_value", "max")
    )
    .reset_index()
)

measure_variability["range"] = (
    measure_variability["maximum"]
    - measure_variability["minimum"]
)

measure_variability.sort_values(
    "range",
    ascending=False
).head(15)

,measureid,measure,category,mean,median,std,minimum,maximum,range
14,DENTAL,Visited dentist or dental clinic in the past y...,Prevention,57.321699,59.1,10.708557,4.9,78.3,73.4
20,FOODSTAMP,Received food stamps in the past 12 months amo...,Health-Related Social Needs,14.048673,12.8,5.933471,3.6,46.6,43.0
19,FOODINSECU,Food insecurity in the past 12 months among ad...,Health-Related Social Needs,17.298391,15.8,6.095419,5.9,46.8,40.9
38,TEETHLOST,All teeth lost among adults aged >=65 years,Health Outcomes,16.145434,15.4,5.903337,3.8,44.6,40.8
0,ACCESS2,Current lack of health insurance among adults ...,Prevention,11.673579,10.4,4.748095,4.0,43.7,39.7
29,MAMMOUSE,Mammography use among women aged 50-74 years,Prevention,73.335571,73.6,4.304889,48.5,86.6,38.1
32,OBESITY,Obesity among adults,Health Outcomes,37.627267,38.2,4.744815,17.1,54.0,36.9
28,LPA,No leisure-time physical activity among adults,Health Risk Behaviors,27.018843,26.5,5.389699,12.2,48.9,36.7
13,CSMOKING,Current cigarette smoking among adults,Health Risk Behaviors,16.342693,16.1,3.542160,6.5,40.3,33.8
17,DISABILITY,Any disability among adults,Disability,32.362077,31.8,5.204851,18.9,52.3,33.4
3,BPHIGH,High blood pressure among adults,Health Outcomes,33.537483,32.8,4.654139,21.0,53.1,32.1
11,COLON_SCREEN,Colorectal cancer screening among adults aged ...,Prevention,57.498218,57.7,4.370783,39.4,71.1,31.7
21,GHLTH,Fair or poor self-rated health status among ad...,Health Status,20.685622,19.9,4.653096,10.4,41.9,31.5
24,HOUSINSECU,Housing insecurity in the past 12 months among...,Health-Related Social Needs,13.968943,12.9,4.255864,5.9,33.6,27.7
36,SLEEP,Short sleep duration among adults,Health Risk Behaviors,37.308018,37.6,4.057472,24.7,51.0,26.3